### ISSUE TITLE
findNodeHandle error from fixItemSectionMeasure

### ISSUE THREAD

**Issue by drewvolz** [sunnylqm/react-native-alphabetlistview#32]
I've come across an issue with the `fixSectionItemMeasure` code. We've implemented a searchbar to feed the `AlphabetListView` a filtered set of data. Feeding the list data quickly caused an error within the [`sectionItem.measure`](https://github.com/sunnylqm/react-native-alphabetlistview/blob/master/components/SectionList.js#L78) logic. This happens x-platform.

```
findNodeHandle(...): Unable to find node handle for unmounted component. 

findNodeHandle
findNodeHandle.js:101 

ProxyComponent.measure
NativeMethodsMixin.js:87

<unknown> SectionList.js:78
```

<img width="387" alt="findnodehandle" src="https://cloud.githubusercontent.com/assets/5240843/25442353/d25e5ff8-2a72-11e7-948b-363c7d83504e.png">

**Comment by ianhowe76** [comment]
My guess is that componentDidUpdate is being called multiple times quickly as you update your list. Due to this the ref is not in the right state to do the measure.

A possible fix would be to set a flag at start of fixSectionItemMeasure and check this before calling sectionItem.measure
Clear the flag in a new componentWillUpdate method

**Comment by drewvolz** [comment]
Thanks @ianhowe76 for the idea.

**Comment by drewvolz** [comment]
We were able to solve our issue by debouncing.
